## 基本介绍

异常处理就是当异常发生时，对异常处理的方式

## 异常处理的方式

1. try-catch-finally
   
   程序员在代码中捕获发生的异常，自行处理
   ```java
   try{
     //代码可能有异常
   }catch(Exception e){
     //捕获到异常
     //1.当异常发生时
     //2.系统将异常封装成Exception对象e，传递给catch
     //3.得到异常对象后，程序员自己处理
     //4.注意。如果没有发生异常，catch代码块不执行
   }finally{
     //1.不管try代码块是否有异常发生，始终要执行finally
     //2.所以，通常将释放资源的代码放在finally
   }
   ```
2. throws
   
   将发生的异常抛出，交给调用者（方法）来处理，最顶级的处理者就是JVM

## try-catch异常处理

### try-catch方式处理异常说明

1. Java提供try和catch块来处理异常，try块用于包含可能出错的代码，catch块用于处理try块中发生的异常，可以根据需要在程序中有多个数量的try-catch块
2. 基本语法
   ```java
   try{
     //可疑代码
     //将异常生成对应的异常对象，传递给catch块
     //ctrl + alt + t可以将代码块包起来
   }catch(异常){
     //对异常的处理
   }//如果没有finally，语法可以通过
   ```

### try-catch方式处理异常注意事项

1. 如果异常发生了，则异常发生后面的代码不会执行，直接进入到catch块
2. 如果异常没有发生，则顺序执行try的代码块，不会进入到catch
3. 如果希望不管是否发生异常，都执行某段代码（比如关闭连接，释放资源等），则使用finally
4. 可以有多个catch语句，捕获不同的异常（进行不同的业务处理），要求父类异常在后，子类异常在前，比如（Exception在后，NullPointerException在前），如果发生异常，只会匹配一个catch。
   ```java
   try{
   }catch(NullPointerException e){
   }catch(Exception e){
   }finally{
   }
   ```
5. 可以进行try-finally配合使用，这种用法相当于没有捕获异常，因此程序会直接崩溃

```java
public class Exception01{
  public static int method(){
    try{
      String[] names = new String[3];
      if(names[1].equals("tom")){//空指针异常
        System.out.println(names[1]);
      }else{
        names[3] = "hspedu";
      }
      return 1;
    }catch(ArrayIndexOutOfBoundsException e){
      return 2;
    }catch(NullPointerException e){//捕获到空指针异常
      return 3;
    }finally{//但finally必须执行，所以没有返回3，而是返回4
      return 4;
    }
  }
}

public static void main(String[] args){
  System.out.println(method());//输出4
}
```

```java
public class Exception01{
  public static int method(){
    int i = 1;
    try{
      i++;
      String[] names = new String[3];
      if(names[1].equals("tom")){//空指针异常
        System.out.println(names[1]);
      }else{
        names[3] = "hspedu";
      }
      return 1;
    }catch(ArrayIndexOutOfBoundsException e){
      return 2;
    }catch(NullPointerException e){//捕获到空指针异常
      return ++i;//i = 3 -->保存临时变量temp = 3，继续执行finally语句
    }finally{
      ++i;//i = 4
      System.out.println("i=" + i);//输出i = 4
    }
  }
}

public static void main(String[] args){
  System.out.println(method());//输出i = 4 ；
                               //    3；
}
```

## try-catch-finally执行顺序小结

1. 如果没有出现异常，则执行try块中所有语句，不执行catch块中语句，如果有finally，最后还需要执行finally里面的语句
2. 如果出现异常，则try块中异常发生后，剩下的语句不再执行。将执行catch块中的语句，如果有finally，最后还要执行finally里面的语句
